BEGIN;

CREATE TABLE IF NOT EXISTS degrees (
   id serial PRIMARY KEY,
   type VARCHAR(10) not null,
   sis_key VARCHAR(35),
   degree VARCHAR (80) NOT NULL
);

-- OPT programs
INSERT INTO degrees (type, sis_key, degree) values 
   ('optional', null, 'BA (Bachelor of Arts)'),
   ('optional', null, 'BARH (Bachelor of Architectural History)'),
   ('optional', null, 'BS (Bachelor of Science)'),
   ('optional', null, 'BSC (Bachelor of Science in Commerce)'),
   ('optional', null, 'BUEP (Bachelor of Urban and Environmental Planning)'),
   ('optional', null, 'DNP (Doctor of Nursing Practice)'),
   ('optional', null, 'EDD (Doctor of Education)'),
   ('optional', null, 'EDS (Education Specialist)'),
   ('optional', null, 'MA (Master of Arts)'),
   ('optional', null, 'MAR (Master of Architecture)'),
   ('optional', null, 'MARH (Master of Architectural History)'),
   ('optional', null, 'MCS (Master of Computer Science)'),
   ('optional', null, 'ME (Master of Engineering)'),
   ('optional', null, 'MED (Master of Education)'),
   ('optional', null, 'MEP (Master of Engineering Physics)'),
   ('optional', null, 'MFA (Master of Fine Arts)'),
   ('optional', null, 'MLA (Master of Landscape Architecture)'),
   ('optional', null, 'MMSE (Master of Materials Science and Engineering)'),
   ('optional', null, 'MPP (Master of Public Policy)'),
   ('optional', null, 'MS (Master of Science)'),
   ('optional', null, 'MSDS (Master of Science in Data Science)'),
   ('optional', null, 'MUEP (Master of Urban and Environmental Planning)'),
   ('optional', null, 'PHD (Doctor of Philosophy');

-- SIS programs
INSERT INTO degrees (type, sis_key, degree) values 
   ('sis', 'DNP', 'DNP (Doctor of Nursing Practice)'),
   ('sis', 'EDD', 'EDD (Doctor of Education)'),
   ('sis', 'MA', 'MA (Master of Arts)'),
   ('sis', 'MAPE', 'MAPE (Master of Arts in Physics Education)'),
   ('sis', 'MAR', 'MAR (Master of Architecture)'),
   ('sis', 'MARH', 'MARH (Master of Architectural History)'),
   ('sis', 'ME', 'ME (Master of Engineering)'),
   ('sis', 'MED', 'MED (Master of Education)'),
   ('sis', 'MFA', 'MFA (Master of Fine Arts)'),
   ('sis', 'MLAR', 'MLA (Master of Landscape Architecture)'),
   ('sis', 'MS', 'MS (Master of Science)'),
   ('sis', 'MUEP', 'MUEP (Master of Urban and Environmental Planning)'),
   ('sis', 'PHD', 'PHD (Doctor of Philosophy)'),
   ('sis', 'SJD', 'SJD (Doctor of Juridical Science)');

CREATE TABLE IF NOT EXISTS  programs (
   id serial PRIMARY KEY,
   type VARCHAR(10) not null,
   sis_key VARCHAR(35),
   program VARCHAR (80) NOT NULL
);

-- OPT programs
INSERT INTO programs (type, sis_key, program) values 
   ('optional', null, 'American Studies'),
   ('optional', null, 'Anthropology'),
   ('optional', null, 'Architectural History'),
   ('optional', null, 'Art'),
   ('optional', null, 'Astronomy'),
   ('optional', null, 'Batten School of Leadership and Public Policy'),
   ('optional', null, 'Biochemistry and Molecular Genetics'),
   ('optional', null, 'Biology'),
   ('optional', null, 'Biomedical Engineering'),
   ('optional', null, 'Biophysics'),
   ('optional', null, 'Chemical Engineering'),
   ('optional', null, 'Chemistry'),
   ('optional', null, 'Civil & Environmental Engineering'),
   ('optional', null, 'Classics'),
   ('optional', null, 'Community Based Undergraduate Research Grant'),
   ('optional', null, 'Computer Engineering'),
   ('optional', null, 'Computer Science'),
   ('optional', null, 'Creative Writing'),
   ('optional', null, 'Curry School of Education'),
   ('optional', null, 'Data Science Institute'),
   ('optional', null, 'Double Hoo Research Grant'),
   ('optional', null, 'Drama'),
   ('optional', null, 'East Asian Studies'),
   ('optional', null, 'Economics'),
   ('optional', null, 'Electrical & Computing Engineering'),
   ('optional', null, 'Engineering Physics'),
   ('optional', null, 'Engineering Science'),
   ('optional', null, 'English'),
   ('optional', null, 'Environmental Sciences'),
   ('optional', null, 'European Studies'),
   ('optional', null, 'Foreign Affairs'),
   ('optional', null, 'French'),
   ('optional', null, 'Geology'),
   ('optional', null, 'Germanic Languages and Literatures'),
   ('optional', null, 'Global Studies'),
   ('optional', null, 'Global Studies-Security & Justice'),
   ('optional', null, 'Harrison Undergraduate Research Award'),
   ('optional', null, 'History'),
   ('optional', null, 'Landscape Architecture'),
   ('optional', null, 'Materials Science & Engineering'),
   ('optional', null, 'Mathematics'),
   ('optional', null, 'McIntire School of Commerce'),
   ('optional', null, 'Mechanical and Aerospace Engineering'),
   ('optional', null, 'Microbiology, Immunology, and Cancer Biology'),
   ('optional', null, 'Middle Eastern and South Asian Languages and Cultures'),
   ('optional', null, 'Molecular Physiology and Biological Physics'),
   ('optional', null, 'Molecular, Cell and Developmental Biology'),
   ('optional', null, 'Music'),
   ('optional', null, 'Neuroscience'),
   ('optional', null, 'Pathology'),
   ('optional', null, 'Pharmacology'),
   ('optional', null, 'Philosophy'),
   ('optional', null, 'Physics'),
   ('optional', null, 'Political & Social Thought'),
   ('optional', null, 'Politics'),
   ('optional', null, 'Psychology'),
   ('optional', null, 'Religious Studies'),
   ('optional', null, 'School of Architecture'),
   ('optional', null, 'School of Data Science'),
   ('optional', null, 'School of Education and Human Development'),
   ('optional', null, 'School of Engineering and Applied Science'),
   ('optional', null, 'School of Nursing'),
   ('optional', null, 'Slavic Languages and Literatures'),
   ('optional', null, 'Sociology'),
   ('optional', null, 'Spanish, Italian, and Portuguese'),
   ('optional', null, 'Statistics'),
   ('optional', null, 'Systems & Information Engineering'),
   ('optional', null, 'Urban and Environmental Planning');

-- SIS programs
INSERT INTO programs (type, sis_key, program) values 
  ('sis', 'ADMIN-EDD', 'Administration and Supervision - School of Education and Human Development'),
  ('sis', 'ADMIN-MED', 'Administration and Supervision - School of Education and Human Development'),
  ('sis', 'ANTHRO-PHD', 'Anthropology - Graduate School of Arts and Sciences'),
  ('sis', 'ARCH-MAR', 'Architecture - School of Architecture'),
  ('sis', 'ARH-MARH', 'Architectural History - School of Architecture'),
  ('sis', 'ARTARC-MA', 'History of Art and Architecture - Graduate School of Arts and Sciences'),
  ('sis', 'ARTARC-PHD', 'History of Art and Architecture - Graduate School of Arts and Sciences'),
  ('sis', 'ASTRON-PHD', 'Astronomy - Graduate School of Arts and Sciences'),
  ('sis', 'BIOL-MA', 'Biology - Graduate School of Arts and Sciences'),
  ('sis', 'BIOL-MS', 'Biology - Graduate School of Arts and Sciences'),
  ('sis', 'BIOL-PHD', 'Biology - Graduate School of Arts and Sciences'),
  ('sis', 'BIOMEN-ME', 'Biomedical Engineering - School of Engineering and Applied Science'),
  ('sis', 'BIOMEN-MS', 'Biomedical Engineering - School of Engineering and Applied Science'),
  ('sis', 'BIOMEN-PHD', 'Biomedical Engineering - School of Engineering and Applied Science'),
  ('sis', 'BIOMOL-PHD', 'Biochemistry and Molecular Genetics - School of Medicine'),
  ('sis', 'BIOP-PHD', 'Biophysics - School of Medicine'),
  ('sis', 'CELL-PHD', 'Cell Biology - School of Medicine'),
  ('sis', 'CHEM-MS', 'Chemistry - Graduate School of Arts and Sciences'),
  ('sis', 'CHEM-PHD', 'Chemistry - Graduate School of Arts and Sciences'),
  ('sis', 'CHEMEN-CGE', 'Chemical Engineering - School of Engineering and Applied Science'),
  ('sis', 'CHEMEN-ME', 'Chemical Engineering - School of Engineering and Applied Science'),
  ('sis', 'CHEMEN-MS', 'Chemical Engineering - School of Engineering and Applied Science'),
  ('sis', 'CHEMEN-PHD', 'Chemical Engineering - School of Engineering and Applied Science'),
  ('sis', 'CIVIL-ME', 'Civil Engineering - School of Engineering and Applied Science'),
  ('sis', 'CIVIL-MS', 'Civil Engineering - School of Engineering and Applied Science'),
  ('sis', 'CIVIL-PHD', 'Civil Engineering - School of Engineering and Applied Science'),
  ('sis', 'CLAS-PHD', 'Classics - Graduate School of Arts and Sciences'),
  ('sis', 'CLNPSY-PHD', 'Clinical Psychology - School of Education and Human Development'),
  ('sis', 'COMPEN-ME', 'Computer Engineering - School of Engineering and Applied Science'),
  ('sis', 'COMPEN-MS', 'Computer Engineering - School of Engineering and Applied Science'),
  ('sis', 'COMPEN-PHD', 'Computer Engineering - School of Engineering and Applied Science'),
  ('sis', 'COMPSC-MCS', 'Computer Science - School of Engineering and Applied Science'),
  ('sis', 'COMPSC-MS', 'Computer Science - School of Engineering and Applied Science'),
  ('sis', 'COMPSC-PHD', 'Computer Science - School of Engineering and Applied Science'),
  ('sis', 'COUNS-EDD', 'Counselor Education - School of Education and Human Development'),
  ('sis', 'COUNS-MED', 'Counselor Education - School of Education and Human Development'),
  ('sis', 'CURRIN-EDD', 'Curriculum and Instruction - School of Education and Human Development'),
  ('sis', 'CURRIN-MED', 'Curriculum and Instruction - School of Education and Human Development'),
  ('sis', 'DRAMA-MFA', 'Drama - Graduate School of Arts and Sciences'),
  ('sis', 'EASIAN-MA', 'East Asian Studies - Graduate School of Arts and Sciences'),
  ('sis', 'ECON-PHD', 'Economics - Graduate School of Arts and Sciences'),
  ('sis', 'EDPSYC-EDD', 'Educational Psychology - School of Education and Human Development'),
  ('sis', 'EDPSYC-MED', 'Educational Psychology - School of Education and Human Development'),
  ('sis', 'EDUC-PHD', 'Education - School of Education and Human Development'),
  ('sis', 'ELECT-CGE', 'Electrical Engineering - School of Engineering and Applied Science'),
  ('sis', 'ELECT-ME', 'Electrical Engineering - School of Engineering and Applied Science'),
  ('sis', 'ELECT-MS', 'Electrical Engineering - School of Engineering and Applied Science'),
  ('sis', 'ELECT-PHD', 'Electrical Engineering - School of Engineering and Applied Science'),
  ('sis', 'ENGL-MA', 'English - Graduate School of Arts and Sciences'),
  ('sis', 'ENGL-PHD', 'English - Graduate School of Arts and Sciences'),
  ('sis', 'ENGPHY-CGE', 'Engineering Physics - School of Engineering and Applied Science'),
  ('sis', 'ENGPHY-MEP', 'Engineering Physics - School of Engineering and Applied Science'),
  ('sis', 'ENGPHY-MS', 'Engineering Physics - School of Engineering and Applied Science'),
  ('sis', 'ENGPHY-PHD', 'Engineering Physics - School of Engineering and Applied Science'),
  ('sis', 'EVSC-MA', 'Environmental Sciences - Graduate School of Arts and Sciences'),
  ('sis', 'EVSC-MS', 'Environmental Sciences - Graduate School of Arts and Sciences'),
  ('sis', 'EVSC-PHD', 'Environmental Sciences - Graduate School of Arts and Sciences'),
  ('sis', 'EXPATH-PHD', 'Experimental Pathology - School of Medicine'),
  ('sis', 'FORAFF-MA', 'Foreign Affairs - Graduate School of Arts and Sciences'),
  ('sis', 'FORAFF-PHD', 'Foreign Affairs - Graduate School of Arts and Sciences'),
  ('sis', 'FRENCH-PHD', 'French - Graduate School of Arts and Sciences'),
  ('sis', 'GERMAN-MS', 'German - Graduate School of Arts and Sciences'),
  ('sis', 'GERMAN-PHD', 'German - Graduate School of Arts and Sciences'),
  ('sis', 'GOVT-MA', 'Government - Graduate School of Arts and Sciences'),
  ('sis', 'GOVT-PHD', 'Government - Graduate School of Arts and Sciences'),
  ('sis', 'HIGHED-EDD', 'Higher Education - School of Education and Human Development'),
  ('sis', 'HIGHED-MED', 'Higher Education - School of Education and Human Development'),
  ('sis', 'HIST-MA', 'History - Graduate School of Arts and Sciences'),
  ('sis', 'HIST-PHD', 'History - Graduate School of Arts and Sciences'),
  ('sis', 'ITAL-MA', 'Italian - Graduate School of Arts and Sciences'),
  ('sis', 'KINES-MED', 'Kinesiology - School of Education and Human Development'),
  ('sis', 'MAE-CGE', 'Mechanical and Aerospace Engineering - School of Engineering and Applied Science'),
  ('sis', 'MAE-ME', 'Mechanical and Aerospace Engineering - School of Engineering and Applied Science'),
  ('sis', 'MAE-MS', 'Mechanical and Aerospace Engineering - School of Engineering and Applied Science'),
  ('sis', 'MAE-PHD', 'Mechanical and Aerospace Engineering - School of Engineering and Applied Science'),
  ('sis', 'MATH-PHD', 'Mathematics - Graduate School of Arts and Sciences'),
  ('sis', 'MATSC-CGE', 'Materials Science - School of Engineering and Applied Science'),
  ('sis', 'MATSC-MMSE', 'Materials Science - School of Engineering and Applied Science'),
  ('sis', 'MATSCI-MS', 'Materials Science - School of Engineering and Applied Science'),
  ('sis', 'MATSCI-PHD', 'Materials Science - School of Engineering and Applied Science'),
  ('sis', 'MICRO-PHD', 'Microbiology - School of Medicine'),
  ('sis', 'MUSIC-PHD', 'Music - Graduate School of Arts and Sciences'),
  ('sis', 'NEURO-PHD', 'Neuroscience - School of Medicine'),
  ('sis', 'NURS-DNP', 'Nursing Practice - School of Nursing'),
  ('sis', 'NURS-PHD', 'Nursing - Graduate School of Arts and Sciences'),
  ('sis', 'PHARM-PHD', 'Pharmacology - School of Medicine'),
  ('sis', 'PHIL-PHD', 'Philosophy - Graduate School of Arts and Sciences'),
  ('sis', 'PHY-PHD', 'Physiology - School of Medicine'),
  ('sis', 'PHYS-MS', 'Physics - Graduate School of Arts and Sciences'),
  ('sis', 'PHYS-PHD', 'Physics - Graduate School of Arts and Sciences'),
  ('sis', 'PLAN-MUEP', 'Urban and Environmental Planning - School of Architecture'),
  ('sis', 'PSYCH-MA', 'Psychology - Graduate School of Arts and Sciences'),
  ('sis', 'PSYCH-PHD', 'Psychology - Graduate School of Arts and Sciences'),
  ('sis', 'RELIG-MA', 'Religious Studies - Graduate School of Arts and Sciences'),
  ('sis', 'RELIG-PHD', 'Religious Studies - Graduate School of Arts and Sciences'),
  ('sis', 'SLAVIC-MA', 'Slavic Languages and Literatures - Graduate School of Arts and Sciences'),
  ('sis', 'SLAVIC-PHD', 'Slavic Languages and Literatures - Graduate School of Arts and Sciences'),
  ('sis', 'SOCIOL-MA', 'Sociology - Graduate School of Arts and Sciences'),
  ('sis', 'SOCIOL-PHD', 'Sociology - Graduate School of Arts and Sciences'),
  ('sis', 'SPAN-PHD', 'Spanish - Graduate School of Arts and Sciences'),
  ('sis', 'SPATH-MED', 'Communication Sciences and Disorders - School of Education and Human Development'),
  ('sis', 'SPCED-MED', 'Special Education - School of Education and Human Development'),
  ('sis', 'STATS-PHD', 'Statistics - Graduate School of Arts and Sciences'),
  ('sis', 'SYSTEM-AM', 'Systems Engineering - School of Engineering and Applied Science'),
  ('sis', 'SYSTEM-CGE', 'Systems Engineering - School of Engineering and Applied Science'),
  ('sis', 'SYSTEM-ME', 'Systems Engineering - School of Engineering and Applied Science'),
  ('sis', 'SYSTEM-MS', 'Systems Engineering - School of Engineering and Applied Science'),
  ('sis', 'SYSTEM-PHD', 'Systems Engineering - School of Engineering and Applied Science'),
  ('sis', 'University of Virginia Libraries', 'University of Virginia Library'),
  ('sis', 'WRITE-MFA', 'Creative Writing - Graduate School of Arts and Sciences'),
  ('sis', 'ANTHRO-MA', 'Anthropology - Graduate School of Arts and Sciences'),
  ('sis', 'BIOLPS-MS', 'Biological and Physical Sciences - School of Medicine'),
  ('sis', 'CLAS-MA', 'Classics - Graduate School of Arts and Sciences'),
  ('sis', 'EDPOL-EDD', 'Education Policy Studies - Graduate School of Arts and Sciences'),
  ('sis', 'FRENCH-MA', 'French - Graduate School of Arts and Sciences'),
  ('sis', 'GERMAN-MA', 'German - Graduate School of Arts and Sciences'),
  ('sis', 'KINES-EDD', 'Kinesiology - School of Education and Human Development'),
  ('sis', 'LAW-SJD', 'Law - School of Law'),
  ('sis', 'MATH-MA', 'Mathematics - Graduate School of Arts and Sciences'),
  ('sis', 'MATH-MS', 'Mathematics - Graduate School of Arts and Sciences'),
  ('sis', 'MESA-MA', 'Middle Eastern and South Asian Studies - Graduate School of Arts and Sciences'),
  ('sis', 'MUSIC-MA', 'Music - Graduate School of Arts and Sciences'),
  ('sis', 'PHYS-MAPE', 'Physics - Graduate School of Arts and Sciences'),
  ('sis', 'SPAN-MA', 'Spanish - Graduate School of Arts and Sciences'),
  ('sis', 'STATS-MS', 'Statistics - Graduate School of Arts and Sciences'),
  ('sis', 'BUSADM-PHD', 'Business Administration - Darden School of Business'),
  ('sis', 'CONSTR-PHD', 'Constructed Environment - School of Architecture'),
  ('sis', 'MECULTE-MA', 'Media, Culture, and Technology - Graduate School of Arts and Sciences'),
  ('sis', 'EUROPE-MA', 'European Studies - Graduate School of Arts and Sciences'),
  ('sis', 'LAND-MLAR', 'School of Architecture'),
  ('sis', 'DS-PHD', 'School of Data Science');

COMMIT;